//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuvrayMonmertNetEdu.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Academy> Academies { get; set; }
        public DbSet<Classroom> Classrooms { get; set; }
        public DbSet<Cycle> Cycles { get; set; }
        public DbSet<Establishment> Establishments { get; set; }
        public DbSet<Evaluation> Evaluations { get; set; }
        public DbSet<Level> Levels { get; set; }
        public DbSet<Period> Periods { get; set; }
        public DbSet<Pupil> Pupils { get; set; }
        public DbSet<Result> Results { get; set; }
        public DbSet<Tutor> Tutors { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Year> Years { get; set; }
    }
}
