//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuvrayMonmertNetEdu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classroom
    {
        public Classroom()
        {
            this.Evaluations = new HashSet<Evaluation>();
            this.Pupils = new HashSet<Pupil>();
        }
    
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public System.Guid User_Id { get; set; }
        public System.Guid Year_Id { get; set; }
        public System.Guid Establishment_Id { get; set; }
    
        public virtual Establishment Establishment { get; set; }
        public virtual User User { get; set; }
        public virtual Year Year { get; set; }
        public virtual ICollection<Evaluation> Evaluations { get; set; }
        public virtual ICollection<Pupil> Pupils { get; set; }
    }
}
