//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuvrayMonmertNetEdu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Period
    {
        public Period()
        {
            this.Evaluations = new HashSet<Evaluation>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime Begin { get; set; }
        public System.DateTime End { get; set; }
        public System.Guid Year_Id { get; set; }
    
        public virtual ICollection<Evaluation> Evaluations { get; set; }
        public virtual Year Year { get; set; }
    }
}
