//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuvrayMonmertNetEdu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pupil
    {
        public Pupil()
        {
            this.Results = new HashSet<Result>();
        }
    
        public System.Guid Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public short Sex { get; set; }
        public System.DateTime BirthdayDate { get; set; }
        public short State { get; set; }
        public System.Guid Tutor_Id { get; set; }
        public System.Guid Classroom_Id { get; set; }
        public System.Guid Level_Id { get; set; }
    
        public virtual Classroom Classroom { get; set; }
        public virtual Level Level { get; set; }
        public virtual Tutor Tutor { get; set; }
        public virtual ICollection<Result> Results { get; set; }
    }
}
