//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuvrayMonmertNetEdu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Classrooms = new HashSet<Classroom>();
            this.Establishments = new HashSet<Establishment>();
            this.Evaluations = new HashSet<Evaluation>();
        }
    
        public System.Guid Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Mail { get; set; }
    
        public virtual ICollection<Classroom> Classrooms { get; set; }
        public virtual ICollection<Establishment> Establishments { get; set; }
        public virtual ICollection<Evaluation> Evaluations { get; set; }
    }
}
